### ISSUE TITLE
Zero-state 

### ISSUE THREAD

**Issue by RukiyaTossou** [BibekMA/fix-the-flow-interactive-website#6]
1. Wat is er?
 Ik had zelf nog geen idee waar de website over ging.  Je ziet de map maar ik weet niet wat ik  precies kan zoeken. Je kan het idee van de rode punten op de map editen.  
3. Waar ben ik?:
 Het is voor mij duidelijk dat ik op de homepagina ben.  Misschien kan je dat nog duidelijker maken voor andere gebruikers, dus met een "straatnaam bordje" dat je op de homepagina bent. 
6. Waar kan ik naar toe? :  
De wegbewijzering is goed. Ik vind de navigatiebalk duidelijk, maar ook de opties die je als gebruiker hebt zijn duidelijk.

**Comment by BibekMA** [comment]
Ik heb een schets gemaakt dat beoordeeld is door een tweedejaars, in de schets aanpassingen op basis van de feedback die ik had gekregen.
